import type { Metadata } from "next";
import "./globals.css";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Suspense
        fallback={
          <div className="flex justify-center items-center h-screen">
            <h1>Loading...</h1>
          </div>
        }
      >
        <body>{children}</body>
      </Suspense>
    </html>
  );
}
